EverythingEverywhereAllAtOnce/Models/ErrorViewModel.cs
namespace EverythingEverywhereAllAtOnce.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

EverythingEverywhereAllAtOnce/Models/PatosPrintModel.cs
using Bussiness;

namespace EverythingEverywhereAllAtOnce.Models;

public class PrintTicketModel
{
    public int Id { get; set; }
    public string? PrintName { get; set; }
    public string? Weight { get; set; }
    public List<Filament> FilamentList { get; set; }
    public int FilamentID { get; set; }
    public List<UserEntity> UserList { get; set; }
    public int UserID { get; set; }
    //missing:
    //public image
    //public file
}

public class Filament
{
    public int FilamentID { get; set; }
    public string FilamentName { get; set; }
    public int FilamentWeight { get; set; }

}

public class PatosPrintUser
{
    public int UserID { get; set; }
    public string UserName { get; set; }
}

EverythingEverywhereAllAtOnce/Models/PrintTicketModel.cs
namespace EverythingEverywhereAllAtOnce.Models;

public class PrintTicketModel
{
    public int Id { get; set; }
    public string? PrintName { get; set; }
    public string? Weight { get; set; }
    public List<Filament> FilamentList { get; set; }
    public int FilamentID { get; set; }
    public List<User> UserList { get; set; }
    public int UserID { get; set; }
    //missing:
    //public image
    //public file
}

public class Filament
{
    public int FilamentID { get; set; }
    public string FilamentName { get; set; }
    public int FilamentWeight { get; set; }

}

public class User
{
    public int UserID { get; set; }
    public string UserName { get; set; }

    //missing:
    //public image
}

EverythingEverywhereAllAtOnce/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using EverythingEverywhereAllAtOnce.Models;

namespace EverythingEverywhereAllAtOnce.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

EverythingEverywhereAllAtOnce/Controllers/PatosPrintController.cs
using Bussiness;
using EverythingEverywhereAllAtOnce.Models;
using Microsoft.AspNetCore.Mvc;

namespace EverythingEverywhereAllAtOnce.Controllers;

public class PatosPrintController : Controller
{
    private Application Current;
    public PatosPrintController(Application application)
    {
        Current = application;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult PrintTicket()
    {
        PrintTicketModel printTicketModel = new PrintTicketModel();
        printTicketModel.FilamentList = GetFilamentList();
        printTicketModel.UserList = UserEntity.GetAllUsersList();

        return View(printTicketModel);
    }

    /// <summary>
    /// Gets all filament in stock
    /// </summary>
    /// <returns>List of all filament in stock</returns>
    private List<Filament> GetFilamentList()
    {
        List<Filament> filamentList = new List<Filament>();

        //TODO: GET FILLAMENT FROM DATABASE
        filamentList.Add(new Filament { FilamentID = 1, FilamentName = "PLA PRETO" });
        filamentList.Add(new Filament { FilamentID = 2, FilamentName = "PLA BRANCO" });
        filamentList.Add(new Filament { FilamentID = 3, FilamentName = "PLA CINZENTO" });

        return filamentList;
    }

    /// <summary>
    /// Adds a new print ticket to database
    /// </summary>
    /// <param name="NewPrintTicket">Filled Model from view</param>
    /// <returns>status and/or redirect</returns>
    [HttpPost]
    private IActionResult NewPrintTicket(PrintTicketModel NewPrintTicket)
    {
        return new JsonResult(true);
        if (ModelState.IsValid)
        { }
    }
}

EverythingEverywhereAllAtOnce/Controllers/ReadMeController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using EverythingEverywhereAllAtOnce.Models;

namespace EverythingEverywhereAllAtOnce.Controllers;

public class ReadMeController : Controller
{
	public ReadMeController()
	{
        
	}

    public IActionResult Index()
    {
         return View();
    }
}

EverythingEverywhereAllAtOnce/Views/PatosPrint/Index.cshtml
<link rel="stylesheet/less" type="text/css" href="styles.less" />
<script src="https://cdn.jsdelivr.net/npm/less"></script>

@{
    ViewData["Title"] = "PatosPrint";
}
<h1>Print Ticket</h1>
<form asp-controller="PatosPrint" asp-action="Index" method="post">
    <div class="form-group">
        <label for="input1">Input 1:</label>
        <input class="form-control" type="text" id="input1" name="Input1" />
    </div>
    <div class="form-group">
        <label for="input2">Input 2:</label>
        <input class="form-control" type="text" id="input2" name="Input2" />
    </div>
    <div class="form-group">
        <label for="input3">Input 3:</label>
        <input class="form-control" type="text" id="input3" name="Input3" />
    </div>
    <div class="form-group">
        <label for="input4">Input 4:</label>
        <input class="form-control" type="text" id="input4" name="Input4" />
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

EverythingEverywhereAllAtOnce/Views/PatosPrint/PrintTicket.cshtml
@using Bussiness;
@model PrintTicketModel

@{
    ViewData["Title"] = "PrintTicket";
}

    <style>
        .image-box {
            width: 200px;
            height: 200px;
            background-image: url("../../../FrontEnd/images/printer.png");
            background-size: cover;
            background-position: center;
            background-repeat: no-repeat;
        }

        .white-text {
            color: white;
        }

        .yellow-text {
            color: rgb(230, 197, 13);
        }

        .input-box {
            width: 200px;
        }
    </style>

    <body class="background">
    <div class="image-box"></div>
        <h1 class="yellow-text">PRINT TICKET</h1>
        <script src="index.js"></script>
        <form method="post" asp-action="NewPrintTicket">
            <label asp-for="PrintName" class="white-text">Print Name:</label><br>
            <input asp-for="PrintName" type="text" class="input-box"><br><br>

            <label asp-for="Weight" class="white-text">Print Name:</label><br>
            <input asp-for="Weight" type="text" class="input-box"><br><br>

            <label asp-for="FilamentID" class="white-text">Select Filament:</label><br>
            @*TODO: ADICIONAR OS REQUIREMENTS (<span asp-validation-for="Name" class="text-danger"></span>)*@

            <select asp-for="FilamentID" class="input-box">
                @foreach(Filament filament in Model.FilamentList)
                {
                    <option value="@filament.FilamentID">@filament.FilamentName</option>
                }
            </select><br><br>

            <select asp-for="UserID" class="input-box">
                @foreach (UserEntity user in Model.UserList)
                {
                    <option value="@user.UserID">@user.UserName</option>
                }
            </select><br><br>

            <button type="submit">Submit</button>
        </form>
    </body>

EverythingEverywhereAllAtOnce/Views/ReadMe/Index.cshtml
<link href="~/css/Notes.css" rel="stylesheet" />

@{
    ViewData["Title"] = "README";
}
<div class="action">
    <form class="action-button" action="patosprint" method="POST">
        <input class="action-button" type="submit"/>
    </form>
</div>

EverythingEverywhereAllAtOnce/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EverythingEverywhereAllAtOnce</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EverythingEverywhereAllAtOnce.styles.css" asp-append-version="true" />
    <link href="https://fonts.cdnfonts.com/css/cascadia-code" rel="stylesheet">

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-page="/Index">PATOS</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="ReadMe" asp-action="Index">README</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="PatosPrint" asp-action="Index">PATOS PRINT</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - EverythingEverywhereAllAtOnce - R3ISilva
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>